version: '3.3'
services:
  redis:
    container_name: redis
    restart: always
    image: redis:latest
    ports:
      - 6379:6379
    volumes:
      - ./redis_data:/data
  auth:
    container_name: auth
    restart: always
    build:
      context: ./auth
      dockerfile: dockerfile
    ports:
      - "8080:8080"
    environment:
      - PORT=8080
  

  producer:
    container_name: producer
    restart: always
    build:
      context: ./producer
      dockerfile: dockerfile
    ports:
      - "8081:8080"
    depends_on:
      - rabbitmq
  consumer:
    container_name: consumer
    restart: always
    build:
      context: ./consumer
      dockerfile: dockerfile
    depends_on:
      - rabbitmq
    tty: true
    stdin_open: true

  rabbitmq:
    container_name: rabbitmq
    restart: always
    image: rabbitmq:3.8.17-management
    ports:
      - 5672:5672  # RabbitMQ default port
      - 15672:15672  # RabbitMQ management console port
    volumes:
      - ./rabbitmq_data:/var/lib/rabbitmq  # Persist data to local directory
  
  mongo:
    container_name: mongo
    restart: always
    image: mongo:5.0.4
    ports:
      - 27017:27017
    environment:
      - MONGO_INITDB_ROOT_USERNAME=chat-admin
      - MONGO_INITDB_ROOT_PASSWORD=chatchat-admin
    volumes:
      - ./mongo_data:/data/db

  # postgres:
  #   container_name: postgres
  #   image: postgres
  #   restart: always
  #   environment:
  #     - POSTGRES_USER=chat-admin
  #     - POSTGRES_PASSWORD=chatchat-admin
  #     - POSTGRES_DB=chatroom_gpt
  #   volumes:
  #     - ./postgres_data:/var/lib/postgresql/data
  #   ports:
  #     - 5432:5432

  chatbot:
    restart: always
    build:
      context: ./chatbot
      dockerfile: dockerfile
    deploy:
      replicas: 10
    
  chatbot-nginx:
    container_name: chatbot-nginx
    image: nginx:latest
    ports:
      - 8090:80
    volumes:
      - ./chatbot-nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - chatbot
  
  chatroom-nginx:
    container_name: chatroom-nginx
    image: nginx:latest
    ports:
      - 8091:80
    # volumes:
    #   - ./chatbot-nginx.conf:/etc/nginx/nginx.conf:ro
    # depends_on:
    #   - chatbot
